### ISSUE TITLE
fatal error messages with git-radar on local untracked branches

### ISSUE THREAD

**Issue by thomasdziedzic** [michaeldfallen/git-prompt#86] opened 2015-10-28 22:59 UTC
```
$ git-radar --bash
fatal: ambiguous argument './master...HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument './master...HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
 git:(some-branch)
```

pushing the branch remotely fixes the issue

```
$ git push -u origin some-branch
Total 0 (delta 0), reused 0 (delta 0)
To git@github.com:PagerDuty/web.git
 * [new branch]      some-branch -> some-branch
Branch some-branch set up to track remote branch some-branch from origin.
```

```
$ git-radar --bash
 git:(some-branch)
```

Some info about my system stats:
os x el capitan version 10.11.1
git version 2.6.2

**Comment by iiro** [comment] 2015-10-29 17:46
Same problem here...

**Comment by hallzy** [comment] 2015-10-29 19:33
Don't think I have the same problem with local untracked branches, but I did see this same error message yesterday when I made a new github repo.

I created the repo on github (repo is empty, no readme etc), I then cloned it. When I enter the repo this message appears, and continues to appear until I have pushed something.

Same similar in that it would be untracked until pushing, but I seem to only see it for new repos.

I am on Ubuntu

**Comment by hallzy** [comment] 2015-10-30 01:56
For me at least, I think the problem is the "git rev-parse --git-dir" command... When I run it I get the error message (perhaps try it on yours as well so we can see if maybe that is what caused it?).

see [this stackoverflow page](https://stackoverflow.com/questions/12267912/git-fatal-ambiguous-argument-head-unknown-revision-or-path-not-in-the-workin).

**Comment by hallzy** [comment] 2015-10-30 02:25
I think I have pinpointed my problem, and perhaps it is similar for everyone else...

in radar-base.sh there are two git commands that cause my error to come up which are:

git rev-list --right-only --count ${remote_branch}...HEAD
git rev-list --left-only --count ${remote_branch}...HEAD

This command lists the commit objects in reverse chronological order...

The first one (right only)  lists the commit objects in reverse order of HEAD in this case, and --left-only does the same but for whatever my ${remote_branch} happens to be... in this case, origin/master

I am guessing the error is because there are no objects in a new repo.

So if we are going to fix this, probably will need a check on the git commands to make sure there is actually something to read, or force an ignore of the error messages...

I noticed in some functions nearby that similar calls are appended by "2>/dev/null || printf '%s' "0""... If we do the same, this will probably go away (for me at least).

Maybe you can check if these are the same calls that are causing problems for you?

What also seems weird about the output you have provided is that the branch it displays is "./master...HEAD"... I have not seen a ./ in a branch before so this could be something else.

Question for the owner: is there a reason that the two calls mentioned above (in functions: commits_ahead_of_remote and commits_behind_of_remote) do not have 2>/dev/null appended, or is this something we can add easily (Just wondering if there is any actual reason that we would not want to add this).

NOTE: I tried appending the 2>/dev/null etc to those two lines mentioned, and the problem does go away for me

**Comment by michaeldfallen** [comment] 2015-10-30 12:32
Yep, I think @hallzy has it. An empty repo causes this problem. Appending `2>/dev/null` fixes. 

@thomasdziedzic It should also fix your problem, though the remote reference seems screwy. Can you run the following commands:

```
> git config --get "branch. some-branch.merge"
> git config --get "branch. some-branch.remote"
```

(assuming your branch is called `some-branch`)

You should see `ref/heads/some-branch` as the merge and `origin` as the remote. If they aren't like that then that might be what's going on. Either a bad sed on git-radars part or a misconfigured remote on your repo?

**Comment by thomasdziedzic** [comment] 2015-11-01 02:40
@michaeldfallen looks like the issue for me might be a misconfigured remote

both of the commands don't print out anything

```
$ git config --get "branch. some-branch.merge"
$ git config --get "branch. some-branch.remote"
```

do you have suggestions on how to fix this?

```
$ git remote -v
origin  git@github.com:Org/repo.git (fetch)
origin  git@github.com:Org/repo.git (push)
```

looks correct to me

**Comment by c5f** [comment] 2015-11-01 17:45
@hallzy Your fix also solves #88 but in a seemingly error-squashing way.  I am trying to figure out if I would like to be notified if one of my tracked branches gets deleted, and burying the error in the bitbucket doesn't leave much room for options there.  Adding a check for tracked branches' existence and adding more emoji would be cool. :tada::confetti_ball::dolphin::whale:

This is totally up to @michaeldfallen, and I admit the consideration for error handling within a small utility like this may be overkill.  `radar-base.sh` already uses `/dev/null` in several places _(`git grep -e \/dev\/null`)_, so I am a-OK with closing #88 if the error is just buried.

---

@thomasdziedzic There should be no space between `branch.` and the branch name.  You can also take a look inside your repository's `.git/config` file to see how each branch is setup.  This is what your `some-branch` configuration should look like on a remote that is not misconfigured according to @michaeldfallen's comment:

```
[branch "some-branch"]
    remote = origin
    merge = refs/heads/some-branch
```

[This function](https://github.com/michaeldfallen/git-radar/blob/master/radar-base.sh#L233-L247) is responsible for retrieving remote branch information and fetches the remote information from your git configuration.  Misconfigured branches would cause odd behavior in there.

**Comment by thomasdziedzic** [comment] 2015-11-01 19:05
I got the following:

```
$ git checkout -b some-branch
Branch some-branch set up to track local branch master.
Switched to a new branch 'some-branch'
```

```
$ git config --get "branch.some-branch.merge"
refs/heads/master
```

```
$ git config --get "branch.some-branch.remote"
.
```

**Comment by michaeldfallen** [comment] 2015-11-04 23:20
@thomasdziedzic sorry about that, I added a space by accident. Yeah that remote config doesn't look right. it should be a name of a remote. Not entirely sure how we fix this. Can you check that the branches are properly configured when you clone a different repo and run `git checkout -b new-branch; git push -u origin new-branch`?

**Comment by michaeldfallen** [comment] 2015-11-04 23:23
@colinsf nice catch with the extra space. My mistake :disappointed:.

**Comment by michaeldfallen** [comment] 2015-11-04 23:26
@colinsf the "missing remote branch" indicator you mentioned is interesting. We have the `upstream ⚡my-branch` to do just that but it only seems to care if its not "set upstream". I suppose rather than squashing the error outputting that would be more informative to the user?

**Closed as completed** 2015-11-05 12:22 UTC

**Comment by c5f** [comment] 2015-11-06 00:58
"Interesting" is about where I left off thinking about it as well.  Maybe throw it into a future feature?
