### ISSUE TITLE
is_cwd_a_dot_git_directory:1: = not found

### ISSUE THREAD

**Issue by oryband** [michaeldfallen/git-prompt#100] opened 2016-01-24 09:08 UTC
Started getting this after updating. Happens when `cd`ing into a any dir in any git repo:

``` bash
$ # i press enter
is_cwd_a_dot_git_directory:1: = not found  # gets printed before prompt shows up again
$
```

I have to turn git-radar off for now because of this :\ Any idea what's the cause?

**Comment by hallzy** [comment] 2016-01-24 09:50
Are you running zsh by chance?

I found [this](http://www.zsh.org/mla/users/2011/msg00161.html) which looks like it gives a similar error because of the `==` in the new function that you referenced. I am unable to reproduce this problem using bash, so if it is a zsh specific thing, that could be why.

**Comment by hallzy** [comment] 2016-01-24 20:38
based on that link, it is possible that surrounding the `==` with single quotes like this `'=='` will resolve the problem. I quickly tried it with bash and it still seems to work.

Maybe you could try adding that and see if that works... If it does, then come back and let us know.

**Comment by oryband** [comment] 2016-01-25 08:05
@hallzy ok i tried wrapping the equals in here https://github.com/michaeldfallen/git-radar/blob/7c5fbb877bf27b20aae3eae1f0eaf668274a8a02/radar-base.sh#L539 and it did the trick. i'l pr the fix in a minute

**Comment by mriehl** [comment] 2016-02-02 15:43
Is it possible to revert the zsh incompatible change until this issue is fixed? I use git-radar as a submodule and it's really a PITA that I cannot update it.

**Comment by michaeldfallen** [comment] 2016-02-03 11:09
Issue fixed. Sorry this has been open so long, I've recently switch jobs and had a fair bit on my plate starting a company etc.

I'd like to explore the idea of opening collaborator access to a few people so git-radar isn't at my mercy alone. It seems that it's used widely enough that the users can't rely on me alone to keep it going (as evidenced by the number of open issues and pull requests).

**Comment by michaeldfallen** [comment] 2016-02-03 11:09
closing as fixed

**Closed as completed by michaeldfallen** 2016-02-03 11:09 UTC

**Comment by mriehl** [comment] 2016-02-03 15:44
:+1: thanks for fixing and thank you very much for your ongoing work on git-radar!
