### ISSUE TITLE
Running export adding it multiple times

### ISSUE THREAD

**Issue by sarthology** [michaeldfallen/git-prompt#52] opened 2015-09-02 09:29 UTC
See
![screen shot 2015-09-02 at 2 57 15 pm](https://cloud.githubusercontent.com/assets/3650216/9627657/1824071a-5183-11e5-9372-db42d2f29b3d.png)

**Comment by michaeldfallen** [comment] 2015-09-02 09:42
That export command appends to PROMPT:

```
export PROMPT="$PROMPT..."
```

So you should expect it to cause the radar to render multiple times if you call it multiple times, since the prompt expands to:

```
> export PROMPT="$PROMPT\$(git-radar --zsh --fetch) "
PROMPT="\$(git-radar --zsh --fetch) "

> export PROMPT="$PROMPT\$(git-radar --zsh --fetch) "
PROMPT="\$(git-radar --zsh --fetch) \$(git-radar --zsh --fetch) "

> export PROMPT="$PROMPT\$(git-radar --zsh --fetch) "
PROMPT="\$(git-radar --zsh --fetch) \$(git-radar --zsh --fetch) \$(git-radar --zsh --fetch) "
```

Closing this issue as it's not a bug or issue in git radar.

**Closed as completed by michaeldfallen** 2015-09-02 09:42 UTC
