### ISSUE TITLE
Calling Formula.sha1 is deprecated!

### ISSUE THREAD

**Issue by selfagency** [michaeldfallen/git-prompt#104] opened 2016-08-02 00:03 UTC
this is broken in homebrew

```
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/michaeldfallen/homebrew-formula/git-radar.rb:7:in `<class:GitRadar>'
Please report this to the michaeldfallen/formula tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/michaeldfallen/homebrew-formula/git-radar.rb:7:in `<class:GitRadar>'
Please report this to the michaeldfallen/formula tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/michaeldfallen/homebrew-formula/git-radar.rb:7:in `<class:GitRadar>'
Please report this to the michaeldfallen/formula tap!
```

**Comment by stefanscheidt** [comment] 2016-08-02 08:20
Also on my machine.

```
$ brew config
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 604f4b6a0785e0295e548e6d033823303da19061
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: dbea1f92e77299620413719aa33f3423c34fe474
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.9.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Users/stefanscheidt/.rbenv/shims/ruby => /Users/stefanscheidt/.rbenv/versions/2.0.0-p648/bin/ruby
Java: 1.8.0_92
OS X: 10.11.6-x86_64
Xcode: 7.3.1
CLT: N/A
X11: N/A
```

**Comment by stefanscheidt** [comment] 2016-08-02 09:46
This is a duplicate of https://github.com/michaeldfallen/homebrew-formula/issues/5.

**Comment by michaeldfallen** [comment] 2016-08-24 15:51
michaeldfallen/homebrew-formula#5 is closed, this should fix this issue. 

Sorry I hadn't addressed it, I'm not using a Mac atm and so don't often see brew issues pop up. Thanks for addressing it.

Closing/

**Closed as completed by michaeldfallen** 2016-08-24 15:51 UTC

**Comment by selfagency** [comment] 2016-08-24 15:54
👍
